services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret-change-me"
    volumes:
      - .:/app
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
